encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.wiki, name="wiki"),
    path("add", views.add, name="add"),
    path("search", views.search, name="search"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("random", views.random, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from . import util
import markdown2
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

#New Article Form
#Contains a edit_mode field for validation if the article exists
class NewArticleForm(forms.Form):
	title = forms.CharField(label="Title")
	body =  forms.CharField(widget=forms.Textarea(attrs={"rows":5, "cols":20}), label="Body (markdown)")
	#Hidden edit mode
	#Used for form validation so a duplicate article isn't created accidentally
	edit_mode = forms.BooleanField(widget=forms.HiddenInput(), initial=False, required=False)

	#https://stackoverflow.com/questions/30227119/extending-form-is-valid
	def clean(self):
		cleaned_data = self.cleaned_data
		title = cleaned_data.get("title")
		body = cleaned_data.get("body")
		edit_mode = cleaned_data.get("edit_mode")
		#https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms
		if(not edit_mode and util.get_entry(title) != None):
			raise forms.ValidationError('Invalid title - article already exists')

		return cleaned_data

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

#Takes the title of the article and renders the HTML from markdown content
#First checks that the title is valid and if not renders a page not found template
def wiki(request, title):
	raw_markdown = util.get_entry(title)
	if(raw_markdown == None):
		return render(request, "encyclopedia/page_not_found.html")
	else:
		return render(request, "encyclopedia/wiki.html", {
				"title": title,
				"entry": markdown2.markdown(raw_markdown)
			})

#Add will render the add page with an article form if it is a get request
#if a post request, it will check the form being valid then either return the original form
#with an error or submit the form and load the newly created page
def add(request):
	if request.method == "POST":
		form = NewArticleForm(request.POST)
		if form.is_valid():
			title = form.cleaned_data["title"]
			body = form.cleaned_data["body"]
			
			util.save_entry(title, body)
			return HttpResponseRedirect(reverse("encyclopedia:wiki" , args=[title]))
		else:
			return render(request, "encyclopedia/add.html", {
					"form": form
				})
	else:
		return render(request, "encyclopedia/add.html", {
				"form": NewArticleForm()
			})

#Searches the database, looking for substrings
#The method finds the q 'get' parameter then checks if its a valid article title
#If an article exists, it redirects to it
#If not, then it uses the find_substrings method to search for any titles that contain
#The string as a substring
def search(request):
	query = request.GET['q']
	entry = util.get_entry(query)
	if entry != None:
		return HttpResponseRedirect(reverse("encyclopedia:wiki" , args=[query]))
	else:
		search_results = util.find_substrings(query)
		return render(request, "encyclopedia/search.html", {
				"query": query,
				"results": search_results
			})

#Calls the add method, but the form by default gets the page's title, body, and edit mode set as "true"
def edit(request, title):
	body = util.get_entry(title)
	return render(request, "encyclopedia/add.html", {
				"form": NewArticleForm(initial={'title': title, 'body': body, 'edit_mode': True})
			})

#Calls a random page, using the util.random_page method
#redirects to the random entry
def random(request):
	title = util.random_page()
	return HttpResponseRedirect(reverse("encyclopedia:wiki" , args=[title]))

encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Add Page
{% endblock %}

{% block body %}
    <form action="{% url 'encyclopedia:add' %}" method="post">
    	{% csrf_token %}
    	{{ form }}
    	<input type="submit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    
    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:wiki'  title=entry%}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}"> Random Page </a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/page_not_found.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Page not found
{% endblock %}

{% block body %}
    <h1>Entry does not exist...</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{query}}
{% endblock %}

{% block body %}
	<h1> Search results for {{query}}: </h1>
	<ul>
		{% for entry in results %}
			<li> <a href="{% url 'encyclopedia:wiki'  title=entry%}">{{ entry }}</a> </li>
	    {% endfor %}
	</ul>
{% endblock %}

encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block nav %}
	<a href="{% url 'encyclopedia:edit'  title=title %}">Edit Page</a>
{% endblock %}

{% block body %}
    {{entry|safe}}
{% endblock %}